#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration
# displays Best School and then Hi on a new line.

u=0

while [ $u -lt 10 ]
do
  if [ $u -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( u++ ))
done
